import json,pathlib,collections,re
B=pathlib.Path('/Users/owenwassmer/dev/agent-journey-visual/slope-reading/audit');m=json.load(open(B/'raw-source-manifest.json'));findings=[]
def add(id,severity,finding,evidence,repair):findings.append(dict(id=id,severity=severity,finding=finding,evidence=evidence,repair=repair))
add('text_dedup','critical','Exact text match is labeled replay and skips whole assistant record before processing its calls. 129 assistant records and 53 user records suppressed; 66 suppressed assistant records have tool_calls. Repetition is not evidence of transport replay.','source/export2.py Hermes seen/hash/continue; raw-source-manifest.json repeated record IDs','Read original native-order records with IDs and active/compacted/display metadata. Preserve all occurrences; infer replay only from identity and source context.')
add('instruction_context','critical','Codex drops developer messages, XML-leading user messages, turn_context, world_state and compaction events. Selected raw sources contain 111 developer messages, 33 XML-leading user messages, 450 turn_context, 114 world_state and 76 compacted records.','source/export2.py Codex response_item-only filter; raw-source-manifest.json','Restored in raw-source. Readers track context changes and summaries at actual exposure positions.')
add('agent_messages','critical','Codex agent_message records are omitted entirely. Many payloads and some outgoing collaboration calls are encrypted in stored source.','source/export2.py recognized types; raw-source Codex response_item agent_message and collaboration calls','Preserved raw; plaintext unavailable must be marked unavailable. Do not reconstruct parent knowledge by silently substituting child full history.')
add('chronology','critical','Global merged ordering truncates timestamps to seconds; source-call IDs, original ordinals and actor metadata are lost. Global availability is not actor exposure.','source/export2.py iso, events.sort, role rendering','Use each actor source order; retain original timestamp, ordinal, call_id, thread/turn IDs, parent and delivery links. Merge for display only.')
add('source_population','high','Exporter selected hard-coded Hermes parents, 10 Codex files by first-line cwd substring, 4 top-level Claude files. 119 Hermes candidate sessions (includes selected parents and child sessions) and 22 Claude nested subagent files exist. This is not a verified complete corpus.','audit/linked-source-candidates.json','Bounded linked-source recovery: inspect named children/forks when establishing action outcomes or delivered context. Do not blanket import unrelated projects.')
add('claude_filtering','high','Claude export omits sidechains, isMeta and XML-leading user text, attachment/system/file-history/queue records, thinking and nontext content.','source/export2.py Claude branch; raw-source-manifest.json','All top-level source events now preserved. Determine visibility from native parent UUIDs/sidechain/attachment semantics rather than role guesses.')
add('hermes_metadata','high','Exporter drops session metadata and row fields such as active, compacted, _compressed_summary, api_content, display_metadata, tool_call_id. Current DB flags do not alone establish historical exposure.','raw-source first metadata rows and full message rows','Preserved all fields under explicit SQLite read transaction. Use native IDs and summary insertion to understand transitions.')
add('payload_storage','resolved','All 15,575 full/ references in all.txt exist in snapshot. Nevertheless the reading spec still references old ACTIONS collapse and omission policy, and full payload existence is not evidence they were read.','source/all.txt; source/full; source/TRACE_SPEC.md','Use full native source reading plus explicit coverage records. Supersede old spec; source/all.txt is a convenience index only.')
add('source_duplicates','high','Codex includes 3 primary 01a0f371 continuation files and 3 explicit child actor files carrying inherited context. UI item_completed may mirror response_item. Equal text is insufficient for dedup.','audit/codex-source-map.json history_base, forked_from_id, subagent_history_start_ordinal','Preserve raw; identify same occurrence from original ordinal/item/call/turn IDs and history_base. Keep inherited child exposure distinct from fresh action. Pure token telemetry may be excluded from semantic reading with counts recorded.')
add('knowledge_vs_artifact','high','A historical artifact can confirm a change without proving the actor had read it. Current repo state cannot substitute for historical context.','Source structure: tool results vs git artifact history','Use received tool/message contents for knowledge; timestamped artifacts for independent outcome verification. Track unavailable original tool output/truncation separately.')
result={'scope':'Structural/provenance audit only; no claim of semantic reading of whole session. Original sources read-only. Raw normalization is extraction, not comprehension.','repaired_export':{'directory':str(B/'raw-source'),'manifest':str(B/'raw-source-manifest.json'),'files':len(m['files']),'events':sum(x['events'] for x in m['files']),'bytes':sum(x['bytes'] for x in m['files']),'schema':m['schema'],'snapshot_note':'Hermes read in one explicit SQLite read transaction; JSONL selected files copied eventwise without omission. Live sources may subsequently grow.'},'findings':findings,'remaining_limits':['Encrypted stored contents unavailable as semantic evidence.','Linked delegate population identified but not yet fully exported or semantically read.','Original runtime may have truncated outputs before persistence; full stored result means full available stored result, not original command output.','Native replay/fork exposure requires identity/ancestry interpretation; raw preserves all records without assuming equal text equals duplication.']}
(B/'source-audit.json').write_text(json.dumps(result,indent=2));print('wrote',B/'source-audit.json')
